[[cupynumeric]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "574c35c143ae6bf73e35e3c198e9eaa7aba35d71"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "70fc437410b1b756e2f96ce6770480a28985fd42ac3618659608757f227b38fc"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.10.0+0/cupynumeric.v25.10.0.x86_64-linux-gnu-cxx11-cuda+none.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fd1de60efdac641bc8ec641849cd893d379923e"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "1ebf70032526f958de228d63197b5fb773174f06823b47abc2bf18b71eed85c6"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.10.0+0/cupynumeric.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.2.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a3a33802f7f551537706420cca7c8d36f70ff58"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "83bea856a43765a7b2a44cf5b86d42bd38f296f3462a74eae914d9f22ac240d4"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.10.0+0/cupynumeric.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.3.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b818689c08b113e935ebd98110e115170fd1a069"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "33c6723810fd18c0ae4443031270337c69d96acbb346717003231b86ef332cf1"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.10.0+0/cupynumeric.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.4.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e4841553b352ef1271e10fc0c000e2dbe453872"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "9cc8ff0af0eaf18cc3afdc368d6bc865663c674706afdb19817aec656c0a7485"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.10.0+0/cupynumeric.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.5.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7661104324c80ec48eacc057089b62a8efbe769b"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "b2765cd238208c9b2b30ae3497272bd3ccc6d7bbb33d352bd4ba7236f6b5b2b0"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.10.0+0/cupynumeric.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.6.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48776a8e082c34add91ce7b03e723a67ce3a22ec"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "d30a549fde00163bbb15973bb668043a53f0c5e86e23083dbf4aa6dd2210e6c9"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.10.0+0/cupynumeric.v25.10.0.x86_64-linux-gnu-cxx11-cuda+12.8.tar.gz"
