[[cupynumeric]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "574c35c143ae6bf73e35e3c198e9eaa7aba35d71"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "70fc437410b1b756e2f96ce6770480a28985fd42ac3618659608757f227b38fc"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.10.1+0/cupynumeric.v25.10.1.x86_64-linux-gnu-cxx11-cuda+none.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8d948353ba344c3bd7678ba1a15b1b1f07fb7a6"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "c99e7bb0ffb48ed50bc1abccaecbba9a1aa99790b8748082c54a9ead6bca285d"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.10.1+0/cupynumeric.v25.10.1.x86_64-linux-gnu-cxx11-cuda+13.0.tar.gz"
