[[cupynumeric]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "09e691a68d74533e13965289a7b2ae801d9eac7b"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "30e9fe8406dfb4bbbdc6af16082decf2cca595f8c50db523ba8adb2c4a817b7f"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.5.0+1/cupynumeric.v25.5.0.x86_64-linux-gnu-cxx11-cuda+none.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.2"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7dbba0c16e3a008a18ca2615936b10838d6515e1"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "30d0190ee57d61fecb48c481c388a2cfa468a4fac102aa9e703c1850417c0d34"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.5.0+1/cupynumeric.v25.5.0.x86_64-linux-gnu-cxx11-cuda+12.2.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.3"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91f7485697f892e78a43f6a1671184e9b4826e38"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "b4f2797d0922535a77c31d67f9ba1910a055792aa873ec0322641b1628d06a84"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.5.0+1/cupynumeric.v25.5.0.x86_64-linux-gnu-cxx11-cuda+12.3.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.4"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51c3742623f5557f42f72b90f43503494b50e4ed"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "a6af3f91e0c8714a7fa01a636b814fb2f167f76efddb1ba726ce86801a2c3318"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.5.0+1/cupynumeric.v25.5.0.x86_64-linux-gnu-cxx11-cuda+12.4.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.5"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7d5ca0c9afa1b4df060e8457c10d1cfcc32f3b59"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "99184cc17948003a3131f7258c8a300e5e7a8802f9d3254aadb9aff331ef3328"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.5.0+1/cupynumeric.v25.5.0.x86_64-linux-gnu-cxx11-cuda+12.5.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.6"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0467929509066f20b62709b7b81d1138e31d6b21"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "f7c67c7d2e84ea573213aad0db2a6e98d50ba1a3067eca9211f0559ac8185917"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.5.0+1/cupynumeric.v25.5.0.x86_64-linux-gnu-cxx11-cuda+12.6.tar.gz"
[[cupynumeric]]
arch = "x86_64"
cuda = "12.8"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1c738635a211572194cc5a27fbc52fe74749fa0"
lazy = true
libc = "glibc"
os = "linux"

    [[cupynumeric.download]]
    sha256 = "07d8a80e28b5179507838138325eae0d40502cc36d3ddabbb162110149ddf385"
    url = "https://github.com/JuliaBinaryWrappers/cupynumeric_jll.jl/releases/download/cupynumeric-v25.5.0+1/cupynumeric.v25.5.0.x86_64-linux-gnu-cxx11-cuda+12.8.tar.gz"
